# zsh theme requires 256 color enabled terminal
# i.e TERM=xterm-256color

PROMPT='%F{red}%(!.#.$)%f'
RPROMPT='%F{yellow}[%?]%f%F{cyan}[%(5~|%-2~/.../%2~|%~)]%f%F{red}[%n@%m]%f'

ZSH_THEME_GIT_PROMPT_PREFIX="%F{154}±|%f%F{124}"
ZSH_THEME_GIT_PROMPT_SUFFIX="%{$reset_color%}"
ZSH_THEME_GIT_PROMPT_DIRTY=" %{$fg[red]%}%B✘%b%F{154}|%f%{$reset_color%}"
ZSH_THEME_GIT_PROMPT_CLEAN=" %{$fg[green]%}✔%F{154}|"
